model_params:
  name: "VAE3D"
  in_channels: 1
  latent_dim: 1024
  beta: 1
  hidden_dims: [8, 32, 128, 512]
  # compression rate = 1/32 = 2 ** 5
  # now: *8->1, *4->1/2, *4->1/2, *4->1/2, *2=1/4
  # information shrink level: [0, 1, 1, 1, 2]
  # only four layer because the size of the patch is changed
  # NOTE: can only grow at rate of 8 *, otherwise the information won't be compressed
  # the final parameter size = hidden_dims[-1] * 2**3
  # e.g. 64 * 8 = 512, the latent_dim should be <= this number

exp_params:
  LR: 0.002 # testing
  batch_size: 36 # better to have a square number. Why?
  max_lr: 0.05
  final_div_factor: 10000

trainer_params:
  max_epochs: 500
  check_val_every_n_epoch: 10

logging_params:
  save_dir: "logs/"
  name: "VAE3D32"
  visualize_interval: 50 # the inteval for outputing visualzation images
  manual_seed: 9001