model_params:
  name: "VAE3D"
  in_channels: 1
  latent_dim: 1024
  hidden_dims: [4, 16, 32, 64]
  beta: 1

exp_params:
  LR: 0.002 # testing
  batch_size: 36 # better to have a squre number. Why?
  # weight_decay: 0.0
  max_lr: 0.05
  final_div_factor: 10000

trainer_params:
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: "VAE3D"
  visualize_interval: 10 # the inteval for outputing visualzation images
  manual_seed: 9001