model_params:
  name: "VAE3D"
  in_channels: 1
  latent_dim: 512
  anneal_steps: 10000

exp_params:
  LR: 0.0002 # testing
  batch_size: 10 # better to have a squre number. Why?
  weight_decay: 0.1

trainer_params:
  gpus: 1
  max_nb_epochs: 2000
  max_epochs: 2000

logging_params:
  save_dir: "logs/"
  name: "VAE3D"
  visualize_interval: 100 # the inteval for outputing visualzation images
  manual_seed: 9001