model_params:
  name: 'VanillaAE'
  in_channels: 1
  latent_dim: 4096
  hidden_dims: [4, 16, 64, 256, 1024]

exp_params:
  LR: 0.0002 # testing
  batch_size: 10 # better to have a squre number. Why?
  weight_decay: 0.1

trainer_params:
  gpus: 1
  max_nb_epochs: 2000
  max_epochs: 2000

logging_params:
  save_dir: "logs/"
  name: "VanillaAE"
  visualize_interval: 100 # the inteval for outputing visualzation images
  manual_seed: 9001